# prometheus.yml
global:
  # Intervalo de scrape predeterminado (cada 15 segundos)
  scrape_interval: 15s
  # Intervalo para evaluar las reglas de alerta
  evaluation_interval: 15s

scrape_configs:
  # La configuración para el propio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # La configuración para la aplicación Spring Boot
  - job_name: 'supportsuite-backend'
    metrics_path: '/actuator/prometheus' # Endpoint de Actuator
    static_configs:
      - targets: ['supportsuite-backend:8080']
        # El nombre del target debe ser el nombre del servicio en docker-compose